# Generated by Django 6.0.6 on 2026-08-08 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0002_alter_message_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentlog",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("support", "Support Agent"),
                    ("tool_call", "Tool Call"),
                    ("tool_result", "Tool Result"),
                    ("manager", "Manager Agent"),
                    ("risk", "Risk Agent"),
                    ("final", "Final Reply"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
